<?php
/**
 * @file
 * Code for the leuven2013_general feature.
 */

include_once 'leuven2013_general.features.inc';

/**
 * Implements hook_block_info().
 */
function leuven2013_general_block_info() {
  $blocks = array();
  $blocks['countdown_timer'] = array(
    'info' => t('Countdown block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['how_to_propose_session'] = array(
    'info' => t('How to propose a session'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function leuven2013_general_block_view($delta = '') {
  module_load_include('inc', 'leuven2013_general', 'leuven2013_general.block');

  $callback = '_leuven2013_general_block_' . $delta;
  if (!function_exists($callback)) {
    return array();
  }

  return $callback();
}
