<?php
/**
 * @file
 * Code for the leuven2013_sponsors feature.
 */

include_once 'leuven2013_sponsors.features.inc';

/**
 * Implements hook_menu().
 */
function leuven2013_sponsors_menu() {
  $items = array();
  $items['sponsorship/%taxonomy_term/apply'] = array(
    'page callback' => 'leuven2013_sponsors_view',
    'page arguments' => array(1),
    // 'page callback' => 'drupal_goto',
    // 'page arguments' => array('mailto:info@drupalcampleuven.be?subject=Interest in DrupalCamp sponsorship ' . ),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Menu callback to goto mailto.
 */
function leuven2013_sponsors_view($term) {
  if (empty($term) || empty($term->name) || empty($term->tid) || $term->vocabulary_machine_name != 'sponsorship_level') {
    return 'No such sponsorship level found';
  }
  else {
    drupal_goto('mailto:info@drupalcampleuven.be?subject=Interest in DrupalCamp ' . $term->name . ' sponsorship&body=<Please insert your company details here>');
  }
}